<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Imperator</text>
        <Action name="create_land_province">
        <icon></icon>
        <text>Create Land Province</text>
        <whatsThis></whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>ctrl+1</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
        <Action name="create_sea_province">
        <icon></icon>
        <text>Create Sea Province</text>
        <whatsThis></whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>ctrl+2</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
        <Action name="create_river_province">
        <icon></icon>
        <text>Create River Province</text>
        <whatsThis></whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>ctrl+3</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
        <Action name="create_impassable_province">
        <icon></icon>
        <text>Create Impassable Province</text>
        <whatsThis></whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>ctrl+4</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>